# Python Day 2

In [12]:
# List comprehension
l1 = [i**2 for i in range(5)]
l2 = [5, 9.4, 4.4, 8.7, 9.7]

print(l1)
print(l2)
print(l1 + l2)
print(3*l1)

In [20]:
l3 = l2*5

In [26]:
# calculate the mean
mean = 0
for element in l3:
    mean = mean + element

mean = mean / len(l3)
print(f'{mean:.5e}')

7.44000e+00


Numpy = Numerical Python

In [29]:
import numpy as np

The most important object in numpy is the numpy array, which is a lot like a list but with extra special features which make it more performant and practical to use.

In [33]:
a1 = np.array(l1)
a2 = np.array(l2)

In [35]:
print(a1)
print(a2)

[ 0  1  4  9 16]
[5.  9.4 4.4 8.7 9.7]


In [48]:
print(l1 + l2)
print(a1 + a2) # adding arrays does the addition element by element instead of concatenating

[0, 1, 4, 9, 16, 5, 9.4, 4.4, 8.7, 9.7]
[ 5.  10.4  8.4 17.7 25.7]


In [50]:
a1 + np.array([1, 2, 3])  # but this means that the arrays should have the same length

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [52]:
lnew = []

for i in range(len(l1)):
    lnew.append(l1[i] + l2[i])

print(lnew)

[5, 10.4, 8.4, 17.7, 25.7]


In [54]:
a1 + a2

array([ 5. , 10.4,  8.4, 17.7, 25.7])

In [56]:
# this is vectorisation: the loop is implicit and you can do all operations element-wise
np.sin(a1)

array([ 0.        ,  0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [60]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [62]:
np_matrix = np.array(matrix)

In [66]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np_matrix.shape

(3, 3)

In [70]:
np.cos(np_matrix) + np_matrix**2 - 6

array([[-4.45969769, -2.41614684,  2.0100075 ],
       [ 9.34635638, 19.28366219, 30.96017029],
       [43.75390225, 57.85449997, 74.08886974]])

We can ask an array about certain of its properties

In [77]:
np_matrix.dtype

dtype('float64')

In [77]:
np.sin(matrix).dtype

dtype('float64')

In [79]:
np_matrix.shape

(3, 3)

In [85]:
np_matrix.ndim

2

In [89]:
print(np_matrix)
print(np_matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [91]:
print(np_matrix.reshape(1, 9))

[[1 2 3 4 5 6 7 8 9]]


In [93]:
mat1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [95]:
mat1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [101]:
print(mat1.reshape(4, 5))
print(mat1.reshape(5, 4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# Three properties of Numpy arrays
## Vectorization

In [108]:
a = np.random.normal(0, 1, size = 10000)
print(a)

[ 0.69134007 -1.05370678 -0.18749959 ...  2.13920277  0.26902399
 -0.07458608]


In [ ]:
# we want to get the list of 1/x

In [110]:
# method 1 : custom function
def explicit_loop(array):
    result = []
    for element in array:
        result.append(1/element)
    return np.array(result)

In [114]:
%timeit explicit_loop(a)

3.39 ms ± 117 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [120]:
# method 2 : list comprehension
%timeit a2 = np.array([1/x for x in a])

2.31 ms ± 493 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [122]:
# method 3 : numpy array vectorisation
%timeit a3 = 1/a

27 μs ± 2.47 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [130]:
max(1/a)

566.849659265584

In [132]:
np.argmax(1/a)

2547

In [155]:
vector3D = np.array(np.random.normal(5, 2, size = (3, 100000)))
vector3D

array([[7.14312319, 5.89656329, 6.70717189, ..., 6.29287278, 3.65116048,
        5.6672553 ],
       [6.05578042, 2.24316258, 2.32360283, ..., 5.43026786, 3.64868116,
        5.43547817],
       [9.17693622, 6.39195847, 4.21422374, ..., 8.24317679, 2.38855569,
        4.23479477]])

In [139]:
vector3D*0.5

array([[0.85549142, 3.58644956, 2.04928878, ..., 2.51140058, 1.70387665,
        4.34711028],
       [2.18310922, 2.95583294, 3.24973766, ..., 1.76146835, 2.58887221,
        2.45390601],
       [1.96061471, 3.01520252, 4.12182507, ..., 1.25988637, 1.52928198,
        2.49018322]])

In [180]:
vector3D.shape

(3, 100000)

In [186]:
np.array([1.5, 7.4, -0.6]).shape

(3,)

In [188]:
vector3D + np.array([[1.5], [7.4], [-0.6]])

array([[ 8.64312319,  7.39656329,  8.20717189, ...,  7.79287278,
         5.15116048,  7.1672553 ],
       [13.45578042,  9.64316258,  9.72360283, ..., 12.83026786,
        11.04868116, 12.83547817],
       [ 8.57693622,  5.79195847,  3.61422374, ...,  7.64317679,
         1.78855569,  3.63479477]])

In [190]:
vector3D + np.array([6, 8])

ValueError: operands could not be broadcast together with shapes (3,100000) (2,) 

In [192]:
vector3D + np.array([[1], [2], [3]])

array([[ 8.14312319,  6.89656329,  7.70717189, ...,  7.29287278,
         4.65116048,  6.6672553 ],
       [ 8.05578042,  4.24316258,  4.32360283, ...,  7.43026786,
         5.64868116,  7.43547817],
       [12.17693622,  9.39195847,  7.21422374, ..., 11.24317679,
         5.38855569,  7.23479477]])