# Introduction to image processing

In [7]:
import numpy as np

def myfunc(x, a, b):
    return a*x + b

In [9]:
x = np.linspace(0, 1, 5)

In [11]:
myfunc(x, 0, 1)

array([1., 1., 1., 1., 1.])

In [13]:
myfunc(x, 6, 41)

array([41. , 42.5, 44. , 45.5, 47. ])

In [15]:
args = [6, 41]
myfunc(x, *args)

array([41. , 42.5, 44. , 45.5, 47. ])